---
builds:
  -
    flags: -tags "static_build"
    ldflags: -w -X main.Version={{.Version}} -X main.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
brews:
  -
    github:
      owner: prologic
      name: homebrew-shops
    homepage: "https://github.io/prologic/shops"
    description: |
      shops is a simple command-line tool written in Go that helps you
      simplify the way you manage configuration across a set of machines.
      shops is your configuration management tool of choice when Chef, Puppet,
      Ansible are all too complicated and all you really want to do is run a
      bunch of regular shell against a set of hosts.
signs:
  -
    artifacts: checksum
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
